apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sethudevspaces 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sethudevspaces 
    spec:
      containers:
        - name: sethudevspaces 
          image: aks1acr.azurecr.io/sethudevspaces
          ports:
          - containerPort: 80